"""SessionStore port — élő session állapot + per-adapter diarizációs állapot,
hogy egy session megszakadt kapcsolat után folytatható legyen (docs/phase1-terv.md
10. szakasz, "megszakadó élő stream")."""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from leiratozo.domain.models import LiveDiarizationState, LiveSession


@runtime_checkable
class SessionStore(Protocol):
    async def create(self, session: LiveSession) -> None: ...
    async def get(self, session_id: str) -> LiveSession | None: ...
    async def update(self, session: LiveSession) -> None: ...
    async def touch(self, session_id: str) -> None: ...
    async def save_diarization_state(self, session_id: str, state: LiveDiarizationState) -> None: ...
    async def get_diarization_state(self, session_id: str) -> LiveDiarizationState: ...
